
name: CiCD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: sudo docker build -t praveen2906/hrms-app:latest .

      - name: Push Docker image
        run: docker push praveen2906/hrms-app:latest

      - name: Pull image from Docker Hub
        run: sudo docker pull praveen2906/hrms-app:latest

      - name: Delete old container
        run: sudo docker rm -f hrms-app-container || true

      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name hrms-app-container praveen2906/hrms-app:latest

      - name: Verify container is running
        run: docker ps


