
name: CiCD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull image from Docker Hub
        run: docker pull praveen2906/hrms-app:latest

      - name: Delete old container
        run: docker rm -f hrms-app-container || true

      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name hrms-app-container praveen2906/hrms-app:latest

      - name: Verify container is running
        run: docker ps



