
name: Deploy React Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@1
        with:
          username: ${{ secrets.Dco_user }}
          password: ${{ secrets.  passsPAS }}

      - name: Build and Push Docker Image
        run: 
      - name: Build Docker image
        run: docker build -t praveen2906/myapp:latest .

      - name: Push Docker image
        run: docker push praveen2906/myapp:latest
  deploy:
    needs: build
    runs-on: self-hosted  # Your EC2 runner

    steps:
      - name: Pull image from Docker Hub
        run: docker pull akashmalviya203/hrms-app:latest

      - name: Delete old container
        run: docker rm -f hrms-app-container || true

      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name hrms-app-container akashmalviya203/hrms-app:latest

